### ISSUE TITLE
spelling error in README

### ISSUE THREAD

**Issue by Tylerli-CL** [cvg/LightGlue#111]
Thank you for your fantastic work; the results are truly amazing. 

I apologize; I don't mean to offend. I just noticed a very minor issue in your README file. It seems there is a spelling error: "The training **end** evaluation code can be found in our training library glue-factory." 

Thank you for your understanding. ：）

**Comment by sarlinpe** [comment]
Fixed in https://github.com/cvg/LightGlue/commit/035612541779b17897aa06d6ff19cb4060111616, thank you!
