### ISSUE TITLE
Illegal License

### ISSUE THREAD

**Issue by axbycc-mark** [cvg/LightGlue#120]
The file [superpoint.py](https://github.com/cvg/LightGlue/blob/main/lightglue/superpoint.py#L1) included in the repo contains the following license.

```
#  Magic Leap, Inc. ("COMPANY") CONFIDENTIAL
#
#  Unpublished Copyright (c) 2020
#  Magic Leap, Inc., All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains the property
# of COMPANY. The intellectual and technical concepts contained herein
# are proprietary to COMPANY and may be covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law.  Dissemination of this information or reproduction of
# this material is strictly forbidden unless prior written permission is
# obtained from COMPANY.  Access to the source code contained herein is
# hereby forbidden to anyone except current COMPANY employees, managers
# or contractors who have executed Confidentiality and Non-disclosure
# agreements explicitly covering such access.
#
# The copyright notice above does not evidence any actual or intended
# publication or disclosure  of  this source code, which includes
# information that is confidential and/or proprietary, and is a trade
# secret, of  COMPANY.   ANY REPRODUCTION, MODIFICATION, DISTRIBUTION,
# PUBLIC  PERFORMANCE, OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS
# SOURCE CODE  WITHOUT THE EXPRESS WRITTEN CONSENT OF COMPANY IS
# STRICTLY PROHIBITED, AND IN VIOLATION OF APPLICABLE LAWS AND
# INTERNATIONAL TREATIES.  THE RECEIPT OR POSSESSION OF  THIS SOURCE
# CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS
# TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE,
# USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
```

I do not believe this file can be legally included in an Apache 2.0 licensed project.

**Comment by sarlinpe** [comment]
From the README:

> SuperPoint follows [a different, restrictive license](https://github.com/magicleap/SuperPointPretrainedNetwork/blob/master/LICENSE) (this includes its pre-trained weights and its [inference file](https://github.com/cvg/LightGlue/blob/main/lightglue/superpoint.py))

In this repo, the Apache 2.0 license applies to files that do not include a different license notice in their header.

**Comment by axbycc-mark** [comment]
Thanks for the clarification. So there are three licenses at play here.
1. The Apache 2.0 License which applies to files in the repo, unless otherwise specified in the particular file.
2. The actual license that applies to the superpoint code, which is mentioned in the README and points to an external repository, and which you have linked above.
3. The license that is mentioned in superpoint.py which is quite a bit more restrictive than the above license.

License 2 (superpoint.py) states 

>  ANY REPRODUCTION, MODIFICATION, DISTRIBUTION,
> # PUBLIC  PERFORMANCE, OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS
> # SOURCE CODE  WITHOUT THE EXPRESS WRITTEN CONSENT OF COMPANY IS
> # STRICTLY PROHIBITED

License 3 gives an academic license. Can you confirm that I should ignore License 2 and consider License 3 to be the one to apply to the superpoint.py file? In that case, would it be okay to copy-paste License 3 over License 2 in my local repository?

**Comment by sarlinpe** [comment]
The file `superpoint.py` is copied verbatim from the original repo. I am not a lawyer so I am unable to comment on whether License 2 or 3 applies.

**Comment by axbycc-mark** [comment]
I understand, thank you. To stay on the safe side, I will just delete that file from my local repo.
