### ISSUE TITLE
Create release/tag for packaging on conda-forge

### ISSUE THREAD

**Issue by Tobias-Fischer** [cvg/LightGlue#129]
Hiya,

Would it be possible to create a release that we can use to package LightGlue on conda-forge?

xref: https://github.com/conda-forge/hloc-feedstock/issues/2

Many thanks!

**Comment by Phil26AT** [comment]
Sure, here it is: https://github.com/cvg/LightGlue/releases/tag/v0.2.

Thank you for bringing LightGlue to conda-forge!

**Comment by Tobias-Fischer** [comment]
Done - https://github.com/conda-forge/lightglue-feedstock

simply “conda install lightglue”
