### ISSUE TITLE
No-match case

### ISSUE THREAD

**Issue by reynoldscem** [cvg/LightGlue#13]
Hi,

It was unclear to me whether your early exit scheme also supports the possibility of rejecting a pair of frames to match at all. Is this something you've looked at? If not would it be a straightforward extension, or do you see caveats?

**Comment by Phil26AT** [comment]
Hi, the early stopping scheme implicitly covers such cases by assigning high confidence to unmatchable points, e.g. if the image pair has no view overlap. In such cases, the network should stop early. However, we did not train LightGlue explicitly on unmatchable image pairs, and thus the network sometimes tries to find (geometrically meaningless, but semantically correct) matches on self-similarities instead (see failure cases in the paper). I agree that this would be a cool and valuable extension!

**Comment by reynoldscem** [comment]
@Phil26AT Thanks for the insights!
