### ISSUE TITLE
Export the results in the form of COLMAP database?

### ISSUE THREAD

**Issue by jianghr-shanghaitech** [cvg/LightGlue#140]
Thank you very much for your work. 
I would like to ask if it is possible to output the matching information of the results in a format similar to the COLMAP database. Thank you again!

**Comment by sarlinpe** [comment]
We have some code for this in https://github.com/cvg/Hierarchical-Localization/
1. Run feature extraction and matching into hdf5 files
2. Convert to a COLMAP database using this: https://github.com/cvg/Hierarchical-Localization/blob/abb252080282e31147db6291206ca102c43353f7/hloc/triangulation.py#L64-L109

**Comment by jianghr-shanghaitech** [comment]
Thank you so much for your prompt response. It has been incredibly helpful to me. Truly appreciate it!
