### ISSUE TITLE
question about rotated images for LightGlue and OpenCV SIFT

### ISSUE THREAD

**Issue by MianMianMeow** [cvg/LightGlue#18]
Hi,
  Thanks for your great work~
  I'm using LightGlue pretrained weight get keypoints from a template image and an input image, and then align the input image with the template by keypoints obtained. I noticed when the input image is rotated(by 90 degrees, 180 degrees and 270 degrees), if I use LightGlue pretrained weight to get the keypoints, the output aligned image is distorted which seems failed. However I tried to use OpenCV SIFT to get the keypoints, the output aligned image is good. 

keypoints got by SIFT
```
sift = cv2.SIFT_create(contrastThreshold=0.02)
...
kp2, des2 = sift.detectAndCompute(target_img, None)
```

align
```
# m_kpts1-> template image, m_kpts0 -> input image
M, mask = cv2.findHomography(m_kpts1, m_kpts0, cv2.RANSAC, 5.0) 
M_r = np.linalg.inv(M)
aligned_img = cv2.warpPerspective(src_img, M_r, (template_w, template_h))
```
Do you know if the problem is caused by that LightGlue pretrained weight does not work good for rotated images? or if there is anything wrong with my code for alignment？Appreciated for suggestions.

**Comment by Phil26AT** [comment]
Hi, LightGlue can handle in-plane rotations up to 45-60° but fails on larger rotations because of missing training data. We are working on a solution to this problem. In the meantime, you can just rotate the input images by 90/180/270 degrees using [np.rot90](https://numpy.org/devdocs/reference/generated/numpy.rot90.html), run feature extraction + matching on each of them, and select the pair with the maximum number of matches.

**Comment by MianMianMeow** [comment]
Thanks for your reply. I'll have a try.

**Comment by qiao89757** [comment]
> 您好，LightGlue 可以处理高达 45-60° 的平面内旋转，但由于缺少训练数据，无法处理更大的旋转。我们正在努力解决这个问题。同时，您可以使用[np.rot90](https://numpy.org/devdocs/reference/generated/numpy.rot90.html)将输入图像旋转 90/180/270 度，对每个图像运行特征提取+匹配，然后选择匹配数量最多的对。

Hello, I really envy you for undertaking such a task. I would like to ask you about the bigger problem. Have you overcome it? I currently have a job where the angles between the images are still large and small, most of them are 90 degrees.
