### ISSUE TITLE
Estimating the H-Matrix (homography) 

### ISSUE THREAD

**Issue by kum0073** [cvg/LightGlue#20]
Hi,

Can you please let me know how to use the matching result to generate the H matrix??

i can see that there are 283 matches  between my image pairs.

![image](https://github.com/cvg/LightGlue/assets/137928422/9a17552a-d66b-491f-8374-3817e2dca1db)

    _matches.size()
    torch.Size([283, 2])_
    
It would be helpful if you can help me with this.

thank you

**Comment by ducha-aiki** [comment]
`H, inliers = cv2.findHomography(m_kpts0, m_kpts1, cv2.USAC_MAGSAC, 0.5, 0.999, 100000)`

**Comment by Phil26AT** [comment]
Another good alternative is [PoseLib](https://github.com/vlarsson/PoseLib/tree/master)'s [`estimate_homography`](https://github.com/vlarsson/PoseLib/tree/master):

`H, info = poselib.estimate_homography(m_kpts0, m_kpts1, {'max_reproj_error': 3.0})`

**Comment by ducha-aiki** [comment]
Yes, we are going to add PoseLib RANSAC to our homography benchmark.
https://github.com/danini/homography-benchmark/tree/main

We actually added it code-wise, but have to tune threshold to get meaningful results.

**Comment by kum0073** [comment]
> Another good alternative is [PoseLib](https://github.com/vlarsson/PoseLib/tree/master)'s [`estimate_homography`](https://github.com/vlarsson/PoseLib/tree/master):
> 
> `H, info = poselib.estimate_homography(m_kpts0, m_kpts1, {'max_reproj_error': 3.0})`

Thank you so much for quick response. 

Currently i have 3 cameras and trying to generate camera parameters (earlier i used Sift and  cv.detail_HomographyBasedEstimator and cv.detail_BundleAdjusterReproj to generate & adjust cam params). It would be helpful if you can let me know if it is possible to estimate the cam params with m_kpts0, m_kpts, matches ??

**Comment by kum0073** [comment]
> `H, inliers = cv2.findHomography(m_kpts0, m_kpts1, cv2.USAC_MAGSAC, 0.5, 0.999, 100000)`

Thank you so much for quick response.

when i used cv.detail_BestOf2NearestMatcher for matching, H matrix generated is different than the above cv2.findHomography method.

Could you please let me know how can i extract features data in cv2.detail_ImageFeatures format
Thank you so much for quick response.
