### ISSUE TITLE
PR to kornia

### ISSUE THREAD

**Issue by ducha-aiki** [cvg/LightGlue#21]
Hi,

I have created a PR to kornia https://github.com/kornia/kornia/pull/2436
Please tell me, if you have any feedback or objections.

Best, Dmytro

**Comment by Skydes** [comment]
Fantastic, thank you Dmytro! We will make some changes to the interface in the next days so better wait and update the PR later.

**Comment by Skydes** [comment]
@ducha-aiki We've made several updates and don't expect new ones for now. Thanks again!

**Comment by ducha-aiki** [comment]
@Skydes @Phil26AT Thank you! I will update the PR and merge into kornia tomorrow or Thursday
