### ISSUE TITLE
Run in google colab

### ISSUE THREAD

**Issue by Itayflymingo** [cvg/LightGlue#23]
can someone make this run in google colab ??

**Comment by yusufaydin0797** [comment]
Hello @Itayflymingo, I don't know if thats what you desire but you can just upload the demo.ipynb to Colab and run the code below by adding  a new cell on top. And then other cells can be executed without any problem.

`!git clone https://github.com/cvg/LightGlue.git`
`!pip install -r /content/LightGlue/requirements.txt`
`%cd /content/LightGlue/`

For example: https://colab.research.google.com/drive/1eH6Vv-K3pq-ben6LI2PcoYHBVbLFWVUu?usp=sharing

**Comment by Itayflymingo** [comment]
That's exactly what I needed thank you!!

**Comment by Phil26AT** [comment]
We added a Colab notebook in PR #22
