### ISSUE TITLE
resize_image() got an unexpected keyword argument 'grayscale'

### ISSUE THREAD

**Issue by Itayflymingo** [cvg/LightGlue#29]
resize_image() function in utils doesn't take a 'grayscale' argument, which explains why you're seeing the "resize_image() got an unexpected keyword argument 'grayscale'". The only arguments this function takes are: "image", "size", "fn", and "interp". If you want to convert the image to grayscale, you'll need to do it either before or after calling resize_image().

[/content/LightGlue/lightglue/utils.py](https://localhost:8080/#) in load_image(path, resize, **kwargs)
    119     image = read_image(path)
    120     if resize is not None:
--> 121         image, _ = resize_image(image, resize, **kwargs)
    122     return numpy_image_to_torch(image)
    123 

TypeError: resize_image() got an unexpected keyword argument 'grayscale'

https://colab.research.google.com/drive/1eH6Vv-K3pq-ben6LI2PcoYHBVbLFWVUu?usp=sharing#scrollTo=frknzZtJM_wb

**Comment by Itayflymingo** [comment]
i understand this was changed in PR22

**Comment by Skydes** [comment]
We indeed changed the path to the notebook. The previous one is deprecated - we will add a notice.
