### ISSUE TITLE
License issue of Superpoint in LightGlue 

### ISSUE THREAD

**Issue by QuanNguyen94** [cvg/LightGlue#38]
Hi, you did a good job, this repo is really help ! I wonder if Superpoint+LightGlue have any issues of license for commercial use ? Does it infringe copyright of Superpoint of MagicLeap ( https://github.com/magicleap/SuperPointPretrainedNetwork/blob/master/LICENSE ). How about the end2end (Superpoint+Lightglue) onnx model (from https://github.com/fabio-sim/LightGlue-ONNX) also ?

**Comment by Skydes** [comment]
Yes, the Apache-2.0 license pertains only to the LightGlue weights (**not to extractor weights** like `superpoint_v1.pth`) and to the code of this repository -- **except for files whose header declares a different license, such as [lightglue/superpoint.py](https://github.com/cvg/LightGlue/blob/main/lightglue/superpoint.py).** https://github.com/cvg/LightGlue/commit/fd12dd7289b678a387e1170e84ae1c4e7574aa92 clarifies this.

**Comment by QuanNguyen94** [comment]
got it, thank for your info.
