### ISSUE TITLE
Release of training and evaluation code

### ISSUE THREAD

**Issue by vrk7** [cvg/LightGlue#40]
When will this be released as the ETA was July?
@Phil26AT @Skydes @ducha-aiki @yusufaydin0797

**Comment by hrago** [comment]
https://github.com/cvg/LightGlue/issues/39#issuecomment-1659924500

**Comment by ikaftan** [comment]
are there any updates on the ETA of the training code release?

**Comment by sarlinpe** [comment]
It's now released: https://github.com/cvg/glue-factory
