### ISSUE TITLE
How should I use this project to complete the pose estimation of the target object？

### ISSUE THREAD

**Issue by GhYang0519** [cvg/LightGlue#44]
I now have: the internal parameter matrix of the camera, the 3D model of the target object, and the rgb image of the target object. My goal is to estimate the pose matrix of the object in the camera coordinate system. I am currently get target object bbox by object detection model and using the pnp method. Can I use this project to obtain the pose of the target object more accurately?

**Comment by Phil26AT** [comment]
Hi @GhYang0519 

Yes, you can use this project to obtain better correspondences for PnP. You would need to build a sparse SfM model for the target object (e.g. from a set of images), and then you can estimate the camera pose of your RGB image in the target object frame (which you can transform to obtain the pose matrix in the camera coordinate system).

You can run all these steps with [hloc](https://github.com/cvg/Hierarchical-Localization/tree/master), LightGlue is already integrated there. Checkout the demo notebook (also available in colab) to get started.

**Comment by GhYang0519** [comment]
thank you for your reply
Can I get the corresponding points between the current RGB image and the template RGB image through LightGlue, and calculate homography transformation through these corresponding points, and then for the template RGB image, I already know the 2D-3D correspondence of the target object in the image, At this point, can I calculate the pose matrix of the target object in the current RGB image?

**Comment by sriharshakoribille** [comment]
Hi @GavinYang5 , I am also trying to solve object pose estimation using Image matching, in the same exact method you proposed above. Were you able to get any good results using Image matching with a 3D model? 
Currently I am maintaining a database of images with poses, without using a 3D model and using LightGlue to get best match and calculate the relative transformation. But I feel its not very scalable and want to use a 3D mesh of the object
