### ISSUE TITLE
Why is Lightglue performing better both in the aspects of inferencing time and accuracy than sp+sg?

### ISSUE THREAD

**Issue by Moreland-cas** [cvg/LightGlue#62]
Great work!
Do you have an idea why the accuracy is becoming better? Is it because you exclude the irrelevant points so that the remained ones won't be affected? Any other potential reasons?

**Comment by Skydes** [comment]
The gain of accuracy mostly comes from fact that LightGlue's training is much more stable than SuperGlue's thanks to improvements in the architecture: softmax+matchability head replacing Sinkhorn+dustbin, relative positional encoding, bi-directional cross attention. Point pruning has negligible effects on the accuracy.

**Comment by sarlinpe** [comment]
> Do you think the consistency issue of feature points is still an important issue for keypoints-based matching methods?

Yes, even DISK is not that good, there is a lot more work to do in this direction.

**Comment by Moreland-cas** [comment]
> > Do you think the consistency issue of feature points is still an important issue for keypoints-based matching methods?
> 
> Yes, even DISK is not that good, there is a lot more work to do in this direction.

Got it  :)
