### ISSUE TITLE
ONNX convert/export

### ISSUE THREAD

**Issue by fabio-sim** [cvg/LightGlue#8]
Hello!

First of all, I would like to applaud your work in pushing the envelope on SOTA local feature matching with LightGlue!

I've actually made an ONNX-compatible version at [https://github.com/fabio-sim/LightGlue-ONNX](https://github.com/fabio-sim/LightGlue-ONNX). It'd be great if you could kindly add a link to it in your readme :)

With ONNX, however, comes some caveats (e.g., difficulty in exporting dynamic control flow). Do let me know if you've got any ideas to support early stopping & adaptive point pruning in ONNX runtime. Have a good day!

**Comment by Phil26AT** [comment]
Hi @fabio-sim, amazing work and also very fast! I added a link to your implementation in the README. Thanks a lot for your contribution.
