### ISSUE TITLE
Choose some points manually

### ISSUE THREAD

**Issue by JaouadROS** [cvg/LightGlue#93]
Is it possible to choose some points manually in one image and run `LighGlue` to find their correspondences?
I want to use `LightGlue` for perspective removing where I have specific points in the reference image.
Thanks a lot.

**Comment by Phil26AT** [comment]
Hi @JaouadROS, I think this is not possible since LG relies on detections in both images, and in your scenario you only have detections in the reference image. But there is other excellent work targeting this problem, e.g. [COTR](https://github.com/ubc-vision/COTR).

**Comment by JaouadROS** [comment]
Thank you @Phil26AT very interesting.
